"""
WeasyPrint Testing Script

This script tests if WeasyPrint is installed correctly and can generate a PDF.
It will create a simple HTML document and convert it to PDF.

Usage:
    python test_weasyprint.py
"""

import os
import sys
import logging
from datetime import datetime

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    datefmt='%Y-%m-%d %H:%M:%S'
)

def main():
    """Test WeasyPrint installation."""
    logging.info("Testing WeasyPrint installation...")
    
    # Create test directory in AppData
    app_data_dir = os.path.join(
        os.environ.get('LOCALAPPDATA', os.path.expanduser('~')),
        "Handyman KPI System"
    )
    test_dir = os.path.join(app_data_dir, "test")
    os.makedirs(test_dir, exist_ok=True)
    
    # Create test HTML file
    html_file = os.path.join(test_dir, "test.html")
    pdf_file = os.path.join(test_dir, "test.pdf")
    
    current_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    html_content = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <title>WeasyPrint Test</title>
        <style>
            body {{ font-family: Arial, sans-serif; margin: 2cm; }}
            h1 {{ color: #0066cc; }}
            p {{ line-height: 1.5; }}
            .footer {{ margin-top: 2cm; font-size: 0.8em; color: #666; }}
        </style>
    </head>
    <body>
        <h1>WeasyPrint Test Document</h1>
        
        <p>This document was generated at: {current_time}</p>
        
        <p>
            This is a test document to verify that WeasyPrint is correctly installed
            and functioning. WeasyPrint is a Python library to convert HTML to PDF.
            It is used in the Handyman KPI System for generating performance reports.
        </p>
        
        <h2>System Information:</h2>
        <ul>
            <li>Python: {sys.version}</li>
            <li>Operating System: {os.name} - {sys.platform}</li>
            <li>Test Directory: {test_dir}</li>
        </ul>
        
        <div class="footer">
            Generated by WeasyPrint Test Script
        </div>
    </body>
    </html>
    """
    
    with open(html_file, 'w') as f:
        f.write(html_content)
    
    logging.info(f"Created test HTML file at: {html_file}")
    
    # Try to import WeasyPrint
    try:
        from weasyprint import HTML
        
        # Generate PDF
        HTML(html_file).write_pdf(pdf_file)
        
        logging.info(f"Successfully generated PDF at: {pdf_file}")
        print(f"\nWeasyPrint is installed and working correctly!")
        print(f"Test PDF generated at: {pdf_file}")
        return 0
    
    except ImportError as e:
        logging.error(f"WeasyPrint is not installed: {e}")
        print("\nWeasyPrint is not installed.")
        print("Please install WeasyPrint using the following command:")
        print("pip install weasyprint")
        return 1
    
    except Exception as e:
        logging.error(f"Error generating PDF: {e}")
        print(f"\nError testing WeasyPrint: {e}")
        print("WeasyPrint is installed but encountered an error.")
        print("This could be due to missing dependencies like GTK3.")
        return 1

if __name__ == "__main__":
    sys.exit(main())
