name: Installer Tests

on:
  push:
    paths:
      - 'installer/**'
      - 'tests/unit/installer/**'
      - '.github/workflows/installer-tests.yml'
  pull_request:
    paths:
      - 'installer/**'
      - 'tests/unit/installer/**'
      - '.github/workflows/installer-tests.yml'

jobs:
  test:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage pytest
        # Install database dependencies
        pip install mysql-connector-python psycopg2-binary
    
    - name: Run tests with coverage
      run: |
        python tests/unit/installer/run_tests.py --cov
    
    - name: Upload coverage report
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report-${{ matrix.python-version }}
        path: tests/unit/installer/coverage_html/